FROM python:3.10.4

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY models ./models
COPY settings.json ./

EXPOSE 8080

CMD [ "mlserver", "start", "." ]
